apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/cronjob.yaml

configMapGenerator:
- name: reconcile-cloudsql-poc-cronjob-configmap-file
  files:
  - configs/config.yaml

secretGenerator:
- name: reconcile-cloudsql-poc-cronjob-secret-file
  files:
    - secrets/sa.json
